# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'b10ec7f3-36b2-40e5-81ca-a25af6b99faf'
  imageRepository: 'vishaltetrisgameapp'
  containerRegistry: 'myapp03.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: DockerCompose@0
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureSubscription: 'Azure subscription 1 (4541453c-061c-4e4d-937c-42be37c2776f)'
        azureContainerRegistry: '{"loginServer":"myapp03.azurecr.io", "id" : "/subscriptions/4541453c-061c-4e4d-937c-42be37c2776f/resourceGroups/MyAPP-RG/providers/Microsoft.ContainerRegistry/registries/Myapp03"}'
        dockerComposeFile: '**/docker-compose.yml'
        action: 'Build services'